package edu.capstone.navisight.caregiver.ui.feature_geofence

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import edu.capstone.navisight.caregiver.model.Geofence
import edu.capstone.navisight.caregiver.domain.geofenceUseCase.AddGeofenceUseCase
import edu.capstone.navisight.caregiver.domain.geofenceUseCase.GetGeofencesByViuUseCase
import com.google.firebase.firestore.GeoPoint
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
import edu.capstone.navisight.caregiver.domain.geofenceUseCase.DeleteGeofenceUseCase

class GeofenceViewModel(
    private val getGeofencesByViuUseCase: GetGeofencesByViuUseCase = GetGeofencesByViuUseCase(),
    private val addGeofenceUseCase: AddGeofenceUseCase = AddGeofenceUseCase(),
    private val deleteGeofenceUseCase: DeleteGeofenceUseCase = DeleteGeofenceUseCase()
) : ViewModel() {

    private val _geofences = MutableStateFlow<List<Geofence>>(emptyList())
    val geofences: StateFlow<List<Geofence>> = _geofences


    private var geofenceJob: Job? = null

    fun loadGeofencesForViu(uid: String) {

        geofenceJob?.cancel()


        geofenceJob = viewModelScope.launch {
            getGeofencesByViuUseCase(uid).collect { geofences ->
                _geofences.value = geofences
            }
        }
    }

    fun clearGeofences() {
        geofenceJob?.cancel()
        _geofences.value = emptyList()
    }

    fun addGeofence(
        viuUid: String,
        name: String,
        location: GeoPoint,
        radius: Double
    ) {
        viewModelScope.launch {
            val newGeofence = Geofence(
                // id will be generated by Firestore
                viuUid = viuUid,
                name = name,
                active = true,
                location = location,
                radius = radius
            )
            addGeofenceUseCase(newGeofence)
        }
    }

    fun deleteGeofence(geofenceId: String) {
        viewModelScope.launch {
            deleteGeofenceUseCase(geofenceId)
        }
    }
}