package edu.capstone.navisight.common.webrtc.service

enum class MainServiceActions {
    START_SERVICE,SETUP_VIEWS,END_CALL,SWITCH_CAMERA,TOGGLE_AUDIO,TOGGLE_VIDEO,TOGGLE_AUDIO_DEVICE,
    TOGGLE_SCREEN_SHARE,STOP_SERVICE,DENY_CALL,ABORT_CALL,IDENTIFY_END_OR_ABORT_CALL
}